#!/usr/bin/env python3

"""
Author: Guilherme Theis

License: MIT

Email: guilhermetheis15@gmail.com

Github: https://github.com/guilhermetheis
"""

"""
Description: This scripts removes the extra columns generated by 
the Eagle ULP and adds the other columns that were not added by
the Eagle ULP.

Usage: ./eagleBOM.py -file samples/sample1.csv 
"""

import os, argparse
import pandas as pd
 
# Allows to enter the file name from the terminal

parser = argparse.ArgumentParser()

parser.add_argument ('-file', required=True, help='file to be fixed i.e: samples/sample.csv')#file to be opened (use it as args.file in code)

args = parser.parse_args() 

# opening the file under the variable f

f = pd.read_csv(args.file,sep=';', usecols=['Qty', 'Value', 'Device', 'Package', 'Parts', 'Description', 'MANUFACTURER', 'PN'])

#print(f) #testing

countRow = f.shape[0]

lineValues = list(range(2,countRow+2))

#print(lineValues) #Testing

f.insert(0,'LINE #', lineValues)
f.insert(9,'NEEDED QTY','')
f.insert(10,'SUPPLIER','')
f.insert(11,'SUPPLIER PN','')
f.insert(12,'STOCK','')
f.insert(13,'MOQ','')
f.insert(14,'PRICE/UNIT','')
f.insert(15,'TOTAL PRICE','')
f.insert(16,'MANUFACTURER','')
f.insert(17,'PN','')
f.insert(18,'SUPPLIER','')
f.insert(19,'SUPPLIER PN','')
f.insert(20,'STOCK','')
f.insert(21,'MOQ','')
f.insert(22,'PRICE/UNIT','')
f.insert(23,'TOTAL PRICE','')

f.to_csv(args.file, index=False) # Saving file (ovewrite)
