#!/usr/bin/env python3

"""
Author: Guilherme Theis

License: MIT

Email: guilhermetheis15@gmail.com

Github: https://github.com/guilhermetheis
"""

"""
Description: This scripts removes the extra columns generated by 
the Eagle ULP and adds the other columns that were not added by
the Eagle ULP.

Usage: ./eagleBOM.py -file samples/sample1.csv 
"""

import os, argparse
import pandas as pd
 
# Allows to enter the file name from the terminal

parser = argparse.ArgumentParser()

parser.add_argument ('-file', required=True, help='file to be fixed i.e: samples/sample.csv')#file to be opened (use it as args.file in code)

args = parser.parse_args() 

# opening the file under the variable f

f = pd.read_csv(args.file,sep=';')

#print(f) #testing

countRow = f.shape[0]

lineValues = list(range(2,countRow+2))

#print(lineValues) #Testing

# Creating the list for equations

equation1 = list()
equation2 = list()

# Creating the string that represents the equation to be inserted with insert()

for x in range (0, countRow): 
	equation1.append('=O'+str(lineValues[x])+'*J'+str(lineValues[x]))
	equation2.append('=W'+str(lineValues[x])+'*J'+str(lineValues[x]))

# Adding columns with equations or blank cells 

f.insert(0,'LINE #', lineValues, True)
f.insert(9,'NEEDED QTY','', True)
f.insert(10,'SUPPLIER','', True)
f.insert(11,'SUPPLIER PN','', True)
f.insert(12,'STOCK','', True)
f.insert(13,'MOQ','', True)
f.insert(14,'PRICE/UNIT','', True)
f.insert(15,'TOTAL PRICE',equation1, True)
f.insert(16,'MANUFACTURER','', True)
f.insert(17,'PN','', True)
f.insert(18,'SUPPLIER','', True)
f.insert(19,'SUPPLIER PN','', True)
f.insert(20,'STOCK','', True)
f.insert(21,'MOQ','', True)
f.insert(22,'PRICE/UNIT','', True)
f.insert(23,'TOTAL PRICE',equation2, True)

f.to_csv(args.file, index=False) # Saving file (ovewrite)
